### ISSUE TITLE
Not putting out .CSV file / use of unexpected semicolon  ";"  instead of comma "," seperator 

### ISSUE THREAD

**Issue by swkong** [igorlogius/tbl2csv#3]

**Comment by swkong** [comment]
The add on is not outputting a .CSV file instead it outputs a text file with semi colon delimiters ";". With that in mind it works just fine.

**Comment by swkong** [comment]
Perhaps someone has changed it from outputting a , to a ; ?

**Comment by swkong** [comment]
Thanks for sharing this tool.  Made my day. I am reformating a data base of fires burning in eastern washington so I can quickly calculate the distance from my home and which direction I will see smoke.

**Comment by igorlogius** [comment]
Hi,
 
you are right, the default csv seperator is a semilcolon. 
Maybe a comma as the name csv implies would be better. 
  
Most tools i use autodetect or let you choose the seperator on import,
so i actualy did not think to much about it.

Still good to hear that the addon could be useful to you.
Thank you kindly for the feedback.

I'll will change/update the seperator as you suggested shortly. 
It makes the most sense.

Have a awesome day.

**Comment by igorlogius** [comment]
Add-on has been updated. 
https://addons.mozilla.org/en-US/firefox/addon/tbl2csv/

The default seperator should now be a comma, as stated in RFC 4180
ref: RFC4180 (https://tools.ietf.org/html/rfc4180)

**Comment by igorlogius** [comment]
Add-on has been updated. 
https://addons.mozilla.org/en-US/firefox/addon/tbl2csv/

The default seperator should now be a comma, as stated in RFC 4180
ref: RFC4180 (https://tools.ietf.org/html/rfc4180)
