### ISSUE TITLE
Printer prints file after import

### ISSUE THREAD

**Issue by swkong** [igorlogius/tbl2csv#4]
I noticed when I went to print a few pages from a .pdf file that the spreadsheet that I last imported with tbl2csv was printing.  It may be doing so by my mistake but I think it could also be from the add on.  I found a neat command line to use in windows to kill the print spooler
***********  at https://thegeekpage.com/force-delete-print-job-in-windows-10/ ************
net stop spooler
del %systemroot%\System32\spool\printers\* /Q /F /S
net start spooler
**************

Again I find your utility so usefull It would be a shame for someone to empty out their toner and paper tray with a big long bunch of stuff they did not want to print?

VR
suwukong@hughes.net

**Comment by igorlogius** [comment]
Hi again,

non of the code inside of the add-on should touch on any printing functionality. 
If i had to guess, i would say, that you queued the printing job (maybe when the printer was still offline or not yet ready to print) and it just got processed a bit later.

**But** if the problem persists (and happens again)  would you be so kind and provide some more information?
 -  Operating System
 -  Firefox Version
 -  Printer Model   

It might not have something todo with the add-on itself, 
but ... there might still be be unintended sideffects, which are  worth a bugreport  at mozilla, microsoft or ... someone else. 

Thanks  in advance,
and i am happy, that my silly little add-on can help out someone.
