### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by swkong** [igorlogius/tbl2csv#5]
Was working a while ago / last year,  I use this to d/load fire data so only in summer.
Win 10 , 64 bit. Mozilla Fierfox

**Comment by igorlogius** [comment]
Hi, i will try to help

please provide some example data  or a url with the table?
If that is not possible, because a login is need just a static(saved)  
html page (or a segment of it) would be fine too.

**Comment by igorlogius** [comment]
@swkong : Did you see my last replay/message?

**Comment by swkong** [comment]
I tried it last night july 13th and it was working again.  The data is from this URL.  Local fires
http://www.wildcad.net/WCWA-NECopen.htm

I noticed also that google maps will show a box with selected location with 15 decimal places.  Neat.

**Comment by igorlogius** [comment]
I also tried to export the Data from  http://www.wildcad.net/WCWA-NECopen.htm
and it seems to work too. [Closing]

PS: 
Glad you also found something that is addionally useful.
