### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by GeniusBroccoli** [igorlogius/tbl2csv#6]
Sometimes it's easier to copy a table to the clipboard than to save it to CSV, open it, copy and paste it into the desired document. However, this applies not only to CSV, but also to HTML, in other words, I would like to see an option to copy to clipboard.

**Comment by igorlogius** [comment]
I'll see what i can do. 

Related notes: 

- Will needs clipboardWrite permission => should be optional
- UI Changes => adding 2 more context options should be fine, but those should only be available when clipboardWrite permission is available if possible

**Comment by igorlogius** [comment]
I didn't make the clipboardWrite permission optional yet (might look into that later)
But version  1.3.17 now has the copy options. 

![snip_20230208-184643](https://user-images.githubusercontent.com/67047467/217610698-d6c64e4b-1e56-4f1a-a232-bd3147a1f1fe.png)

Hope it helps.
