### ISSUE TITLE
double s ('ss') is replaced by a space after export

### ISSUE THREAD

**Issue by mathieubossaert** [igorlogius/tbl2csv#7]
**Describe the bug**
Exporting an html table to text or html transforms 'ss' strings to space

I am using Firefox 114.0.2 (64 bits) on ubuntu.

Here a screenshot of the problem. Anyway, thanks a lot for this great extension !!!
![Capture d’écran du 2023-06-21 11-37-47](https://github.com/igorlogius/tbl2csv/assets/1642645/c27bdd9b-360f-4b1b-a1f2-e3927153f90a)

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to report this issue. I'll try to help out as best i can. 

Can you please share the URL to the table or if that is not possible an extract of the HTML source would also be ok. With either i'll try to reproduce the error and come back with an analysis.

>  thanks a lot for this great extension !!!

You are welcome. Nice getting some feedback and hearing that people are actually using it and that it is a little useful.

**Comment by mathieubossaert** [comment]
Of course : 
https://dashboards.cen-occitanie.org/embed/query/554/visualization/1156?api_key=h6dVS91vEtS6vlb7VdmehFrUJDa9ILhfChVxupwA&

`Nice getting some feedback and hearing that people are actually using it and that it is a little useful.`

I know, I already had unexpected feedbacks about some work I shared :-)
Your extension will be a good add-on for our my colleagues (nature conservation NGO in France) who want to download our redash crosstab dashboards !

**Comment by igorlogius** [comment]
This is definitely a Bug. 
Seems like i made a mistake when writing the multi space regular expression. 

Should be fixed with version `1.3.19`
